on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
name: Flatpak build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: palette.flatpak
        manifest-path: .flatpak/flathub/dev.lukebriggs.pepys.yml
        cache-key: flatpak-builder-${{ github.sha }}