name: Test Flatpak

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Test-Flatpak-Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup flatpak
      - name: Flatpak setup
        run: |
          sudo apt install flatpak
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --noninteractive org.kde.Platform//6.2 io.qt.qtwebengine.BaseApp//6.2

      # Build flatpak
      - name: Build flatpak
        run: |
          flatpak-builder build ${{ github.workspace }}/.flatpak/flathub/dev.lukebriggs.pepys.yml
